name: binance-trade-bot
on:
  push:
    branches:
      - master
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          IMG=binance-trade-bot
          OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE=ghcr.io/${OWNER}/${IMG}" >> $GITHUB_ENV
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - name: Upload docker compose file
        uses: appleboy/scp-action@master
        with:
          host: home.utku.me
          port: 2322
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          command_timeout: 1m
          source: "docker-compose.deploy.yml"
          target: "deployment/binance-trade-bot"
          rm: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          # platforms: linux/arm64v8
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ env.GIT_SHA }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest
          cache-to: type=inline          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: home.utku.me
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 2322
          script_stop: true
          sync: true
          command_timeout: 1m
          script: |
            mkdir -p /home/ubuntu/data/binance-trade-bot/db
            mkdir -p /home/ubuntu/config/binance-trade-bot
            echo ${{ secrets.USER_CFG }} | base64 --decode > /home/ubuntu/config/binance-trade-bot/user.cfg
            echo ${{ secrets.SUPPORTED_COIN_LIST }} | base64 --decode > /home/ubuntu/config/binance-trade-bot/supported_coin_list
            echo ${{ secrets.APPRISE_CFG }} | base64 --decode > /home/ubuntu/config/binance-trade-bot/apprise.yml     
            sudo docker login -u ${{ github.repository_owner }} -p ${{ secrets.CR_TOKEN }} ghcr.io
            sudo DOCKER_IMAGE="${{ env.IMAGE }}:${{ env.GIT_SHA }}" docker stack deploy -c /home/ubuntu/deployment/binance-trade-bot/docker-compose.deploy.yml binance-trade-bot --resolve-image never --with-registry-auth
            